version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask-api:
    build: .
    container_name: flask-api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=react-pf
      - JWT_SECRET_KEY=123456
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - mongo

volumes:
  mongo_data:
